find_path(SOIL_INCLUDE_DIR SOIL.h PATH_SUFFIXES SOIL)
find_library(SOIL_LIBRARY NAMES SOIL)

set(SOIL_INCLUDE_DIRS ${SOIL_INCLUDE_DIR})
set(SOIL_LIBRARIES ${SOIL_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SOIL REQUIRED_VARS SOIL_INCLUDE_DIR SOIL_LIBRARY)

if(SOIL_FOUND AND NOT TARGET SOIL::SOIL)
  add_library(SOIL::SOIL UNKNOWN IMPORTED)
  set_target_properties(SOIL::SOIL PROPERTIES
    IMPORTED_LOCATION "${SOIL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${SOIL_INCLUDE_DIRS}")
endif()

mark_as_advanced(SOIL_INCLUDE_DIR SOIL_LIBRARY)
